logging:
  level: INFO

exchanges:
  - binance
  - kraken
  - coinbasepro

arbitrage:
  symbols:
    - ICP/USDT
    - SOL/USDT
    - BASE/USDT
    - NEAR/USDT
  threshold: 0.5  # Minimum percentage profit for arbitrage
  trade_amount: 1  # Default amount to trade

email:
  enabled: true
  smtp_server: smtp.live.co.uk
  smtp_port: 587
  username: email@live.co.uk
  password: xxxx
  recipient: recipient@test.com

order_book:
  depth: 5

fees:
  taker_fee: 0.1

risk_management:
  max_risk_percentage: 5
  per_symbol: true

telegram:
  enabled: true
  bot_token: xxx
  chat_id: xxx

retry:
  max_retries: 3
  delay: 1

efk:
  logstash_host: "localhost"  # Need to replace with your logstash host
  logstash_port: 5000         
